[pytest]    
# 这是配置文件的节头 告诉 pytest 以下配置属于 pytest
#默认命令行参数
addopts =   
    -V
    -s
    --alluredir=./reports/allure-results
    --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*